audit:
  history-size: 100
  page-size: 20
  compress: true
  backend: memory
  file-path: audit-store.ser
  enabled: true

mapping:
  pretty-print: false
  escape-non-ascii: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,refresh
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: db,ping
        liveness:
          include: ping

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: xml-json
  config:
    import: "optional:configserver:http://config-server:8888"
