ALTER TABLE audit_entry
    ADD COLUMN IF NOT EXISTS xml_key VARCHAR(512),
    ADD COLUMN IF NOT EXISTS json_key VARCHAR(512),
    ALTER COLUMN xml_data DROP NOT NULL,
    ALTER COLUMN json_data DROP NOT NULL;

